stages:
  - validate
  - plan
  - apply

variables:
  TF_VERSION: "1.1.0"
  TF_ADDRESS: "https://example.com"
  TF_STATE_NAME: "terraform.tfstate"

cache:
  paths:
    - .terraform/

before_script:
  - apk add --no-cache curl jq python3 py3-pip
  - pip3 install awscli

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=plan.tfplan
  artifacts:
    paths:
      - plan.tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve plan.tfplan
